In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('data-lcs.csv')
df.shape

(3717, 9)

In [5]:
df.sort_values('ratio', ascending=False, inplace=True)
df.head(n=20)

,symbol,expiration_date,p1,p2,p3,p4,max_loss,max_profit,ratio
2800,ROKU,2021-06-11,345.0,347.5,350.0,352.5,2.0,248.0,124.00
3279,TSIA,2021-06-18,10.0,12.5,15.0,17.5,2.0,248.0,124.00
226,AMZN,2021-06-04,3220.0,3225.0,3230.0,3235.0,5.0,495.0,99.00
3010,SPCE,2021-06-11,31.0,32.0,33.0,34.0,1.0,99.0,99.00
1231,FATE,2021-06-18,75.0,80.0,85.0,90.0,5.0,495.0,99.00
24,ABBV,2021-06-25,113.0,114.0,115.0,116.0,1.0,99.0,99.00
3388,UPST,2021-06-18,145.0,150.0,155.0,160.0,5.0,495.0,99.00
3467,VMW,2021-06-11,157.5,160.0,162.5,165.0,3.0,247.0,82.33
3281,TSLA,2021-06-11,625.0,627.5,630.0,632.5,3.0,247.0,82.33
1645,HYLN,2021-06-11,10.5,11.0,11.5,12.0,1.0,49.0,49.00
677,CHPT,2021-06-18,24.0,24.5,25.0,25.5,1.0,49.0,49.00
1617,HSBC,2021-06-25,32.0,32.5,33.0,33.5,1.0,49.0,49.00
3542,WDC,2021-06-11,75.0,75.5,76.0,76.5,1.0,49.0,49.00
2164,MOMO,2021-06-25,14.0,14.5,15.0,15.5,1.0,49.0,49.00
596,CAR,2021-06-18,87.5,90.0,92.5,95.0,5.0,245.0,49.00
728,CLVS,2021-06-25,5.0,5.5,6.0,6.5,1.0,49.0,49.00
34,ABNB,2021-06-04,140.0,141.0,142.0,143.0,2.0,98.0,49.00
2350,NSC,2021-06-25,280.0,282.5,285.0,287.5,5.0,245.0,49.00
1063,DOW,2021-06-18,68.0,68.5,69.0,69.5,1.0,49.0,49.00
2978,SNOW,2021-06-25,237.5,240.0,242.5,245.0,5.0,245.0,49.00